version: 2
project_name: vpd
before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
builds:
  - binary: vpd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: "{{ .ProjectName }}"
    repository:
        owner: VojtechPastyrik
        name: homebrew-tap
    homepage: "https://github.com/VojtechPastyrik/vpd"
    url_template: "https://github.com/VojtechPastyrik/vpd/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    directory: Formula
    caveats: "How to use this binary: https://github.com/VojtechPastyrik/vpd"
    description: "Vojtech Pastyrik Utils"
    install: |
      bin.install "vpd"

    test: |
      system "#{bin}/vpd version"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "vojtechpastyrik/vpd:{{ .Tag }}"
      - "vojtechpastyrik/vpd:latest"
    dockerfile: Dockerfile.goreleaser
    ids:
      - vpd
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/VojtechPastyrik/vpd"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=repository=https://github.com/VojtechPastyrik/vpd"
      - "--label=maintainer=Vojtech Pastyrik <vojtech@pastyrik.dev>"
  - goos: linux
    goarch: arm64
    image_templates:
      - "vojtechpastyrik/vpd:{{ .Tag }}-arm64v8"
      - "vojtechpastyrik/vpd:latest-arm64v8"
    dockerfile: Dockerfile.goreleaser.arm64v8
    ids:
      - vpd
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/VojtechPastyrik/vpd"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=repository=https://github.com/VojtechPastyrik/vpd"
      - "--label=maintainer=Vojtech Pastyrik <vojtech@pastyrik.dev>"


changelog:
  filters:
    exclude:
      - '^VERSION'

nfpms:
  - id: vpd-deb
    package_name: vpd
    formats:
      - deb
    maintainer: "Vojtech Pastyrik <vojtech@pastyrik.dev>"
    description: "Vojtech Pastyrik Utils"
    homepage: "https://github.com/VojtechPastyrik/vpd"
    license: "MIT"
    vendor: "Vojtech Pastyrik"
    section: "utils"
    priority: "optional"
    conflicts:
      - vpd-old
    replaces:
      - vpd-old
    provides:
      - vpd
    dependencies:
      - libc6
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}.deb"
    bindir: /usr/bin
  - id: vpd-rpm
    package_name: vpd
    formats:
      - rpm
    maintainer: "Vojtech Pastyrik <vojtech@pastyrik.dev>"
    description: "Vojtech Pastyrik Utils"
    homepage: "https://github.com/VojtechPastyrik/vpd"
    license: "MIT"
    vendor: "Vojtech Pastyrik"
    section: "utils"
    priority: "optional"
    conflicts:
      - vpd-old
    replaces:
      - vpd-old
    provides:
      - vpd
    dependencies:
      - libc6
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}.rpm"
    bindir: /usr/bin