version: 2
project_name: vp-utils
before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
builds:
  - binary: vp-utils
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: "{{ .ProjectName }}"
    repository:
        owner: VojtechPastyrik
        name: homebrew-tap
    homepage: "https://github.com/VojtechPastyrik/vp-utils"
    url_template: "https://github.com/VojtechPastyrik/vp-utils/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    directory: Formula
    caveats: "How to use this binary: https://github.com/VojtechPastyrik/vp-utils"
    description: "Vojtech Pastyrik Utils"
    install: |
      bin.install "vp-utils"

    test: |
      system "#{bin}/vp-utils version"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "vojtechpastyrik/vp-utils:{{ .Tag }}"
      - "ghcr.io/vojtechpastyrik/vp-utils:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    ids:
      - vp-utils
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/vojtechpastyrik/vp-utils"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=repository=https://github.com/vojtechpastyrik/vp-utils"
      - "--label=maintainer=Vojtech Pastyrik <vojtech@pastyrik.dev>"
  - goos: linux
    goarch: arm64
    image_templates:
      - "vojtechpastyrik/vp-utils:{{ .Tag }}-arm64v8"
    dockerfile: Dockerfile.goreleaser.arm64v8
    ids:
      - vp-utils
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/vojtechpastyrik/vp-utils"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=repository=https://github.com/vojtechpastyrik/vp-utils"
      - "--label=maintainer=Vojtech Pastyrik <vojtech@pastyrik.dev>"


changelog:
  filters:
    exclude:
      - '^VERSION'